# Generated by Django 3.1.14 on 2022-04-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0003_learning_prerequisite_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='course',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
