# Generated by Django 3.1.14 on 2022-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedtls',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursedtls',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
