# Generated by Django 3.1.14 on 2022-04-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0009_auto_20220410_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedtls',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
