# Generated by Django 3.1.14 on 2022-04-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0010_auto_20220410_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
