# Generated by Django 3.1.14 on 2022-04-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0012_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
