# Generated by Django 3.1.14 on 2022-04-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0014_payment_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
