# Generated by Django 3.1.14 on 2022-04-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0015_auto_20220413_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futureskill.coursedtls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futureskill.registration')),
            ],
        ),
    ]
