# Generated by Django 3.1.14 on 2022-04-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='futureskill.usercourse'),
        ),
    ]
