# Generated by Django 3.1.14 on 2022-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0018_payment_user_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_info',
        ),
    ]
