# Generated by Django 3.1.14 on 2022-04-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0020_couponcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='couponcode',
        ),
    ]
