# Generated by Django 3.1.14 on 2022-04-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futureskill', '0021_delete_couponcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futureskill.coursedtls')),
            ],
        ),
    ]
